// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABf8cKIGmR-0kLzqYaXWcSeHWpoGc-7QI',
    appId: '1:1038055476346:web:6606eb4e4a2c56a3acbfc3',
    messagingSenderId: '1038055476346',
    projectId: 'gestion-ecole-app',
    authDomain: 'gestion-ecole-app.firebaseapp.com',
    storageBucket: 'gestion-ecole-app.firebasestorage.app',
    measurementId: 'G-1HVYCL0CFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcMJPDM_9lC7sSLYSICDv5Y1DHnRN1Nzs',
    appId: '1:1038055476346:android:078e95009476448aacbfc3',
    messagingSenderId: '1038055476346',
    projectId: 'gestion-ecole-app',
    storageBucket: 'gestion-ecole-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgTv1HP0DWCmsTuHDdK8NEnkweeSRzIw0',
    appId: '1:1038055476346:ios:b37192f4a93f32f0acbfc3',
    messagingSenderId: '1038055476346',
    projectId: 'gestion-ecole-app',
    storageBucket: 'gestion-ecole-app.firebasestorage.app',
    iosBundleId: 'com.example.gestionEcole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgTv1HP0DWCmsTuHDdK8NEnkweeSRzIw0',
    appId: '1:1038055476346:ios:b37192f4a93f32f0acbfc3',
    messagingSenderId: '1038055476346',
    projectId: 'gestion-ecole-app',
    storageBucket: 'gestion-ecole-app.firebasestorage.app',
    iosBundleId: 'com.example.gestionEcole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABf8cKIGmR-0kLzqYaXWcSeHWpoGc-7QI',
    appId: '1:1038055476346:web:b6f66f4f5063b4ccacbfc3',
    messagingSenderId: '1038055476346',
    projectId: 'gestion-ecole-app',
    authDomain: 'gestion-ecole-app.firebaseapp.com',
    storageBucket: 'gestion-ecole-app.firebasestorage.app',
    measurementId: 'G-CVF1G8E2VK',
  );
}
